/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdminWhereUniqueInput } from "../../admin/base/AdminWhereUniqueInput";
import { ValidateNested, IsOptional, IsInt, IsNumber } from "class-validator";
import { Type } from "class-transformer";
import { ItemUpdateManyWithoutSalesInput } from "./ItemUpdateManyWithoutSalesInput";
import { ManagerWhereUniqueInput } from "../../manager/base/ManagerWhereUniqueInput";
@InputType()
class SaleUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AdminWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdminWhereUniqueInput)
  @IsOptional()
  @Field(() => AdminWhereUniqueInput, {
    nullable: true,
  })
  admin?: AdminWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ItemUpdateManyWithoutSalesInput,
  })
  @ValidateNested()
  @Type(() => ItemUpdateManyWithoutSalesInput)
  @IsOptional()
  @Field(() => ItemUpdateManyWithoutSalesInput, {
    nullable: true,
  })
  item?: ItemUpdateManyWithoutSalesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  itemQuantity?: number;

  @ApiProperty({
    required: false,
    type: () => ManagerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ManagerWhereUniqueInput)
  @IsOptional()
  @Field(() => ManagerWhereUniqueInput, {
    nullable: true,
  })
  manager?: ManagerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  sellingPrice?: number;
}
export { SaleUpdateInput };
