/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import {
  Prisma,
  Admin,
  Customer,
  Item,
  Manager,
  Sale,
  Store,
  Supplier,
} from "@prisma/client";

export class AdminServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.AdminFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminFindManyArgs>
  ): Promise<number> {
    return this.prisma.admin.count(args);
  }

  async findMany<T extends Prisma.AdminFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminFindManyArgs>
  ): Promise<Admin[]> {
    return this.prisma.admin.findMany(args);
  }
  async findOne<T extends Prisma.AdminFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminFindUniqueArgs>
  ): Promise<Admin | null> {
    return this.prisma.admin.findUnique(args);
  }
  async create<T extends Prisma.AdminCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminCreateArgs>
  ): Promise<Admin> {
    return this.prisma.admin.create<T>(args);
  }
  async update<T extends Prisma.AdminUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminUpdateArgs>
  ): Promise<Admin> {
    return this.prisma.admin.update<T>(args);
  }
  async delete<T extends Prisma.AdminDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminDeleteArgs>
  ): Promise<Admin> {
    return this.prisma.admin.delete(args);
  }

  async findCustomer(
    parentId: string,
    args: Prisma.CustomerFindManyArgs
  ): Promise<Customer[]> {
    return this.prisma.admin
      .findUnique({
        where: { id: parentId },
      })
      .customer(args);
  }

  async findItem(
    parentId: string,
    args: Prisma.ItemFindManyArgs
  ): Promise<Item[]> {
    return this.prisma.admin
      .findUnique({
        where: { id: parentId },
      })
      .item(args);
  }

  async findManager(
    parentId: string,
    args: Prisma.ManagerFindManyArgs
  ): Promise<Manager[]> {
    return this.prisma.admin
      .findUnique({
        where: { id: parentId },
      })
      .manager(args);
  }

  async findSales(
    parentId: string,
    args: Prisma.SaleFindManyArgs
  ): Promise<Sale[]> {
    return this.prisma.admin
      .findUnique({
        where: { id: parentId },
      })
      .sales(args);
  }

  async findStores(
    parentId: string,
    args: Prisma.StoreFindManyArgs
  ): Promise<Store[]> {
    return this.prisma.admin
      .findUnique({
        where: { id: parentId },
      })
      .stores(args);
  }

  async findSupplier(
    parentId: string,
    args: Prisma.SupplierFindManyArgs
  ): Promise<Supplier[]> {
    return this.prisma.admin
      .findUnique({
        where: { id: parentId },
      })
      .supplier(args);
  }
}
