/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import {
  Prisma,
  Manager,
  Customer,
  Item,
  Sale,
  Supplier,
  Admin,
  Store,
} from "@prisma/client";

export class ManagerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ManagerFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ManagerFindManyArgs>
  ): Promise<number> {
    return this.prisma.manager.count(args);
  }

  async findMany<T extends Prisma.ManagerFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ManagerFindManyArgs>
  ): Promise<Manager[]> {
    return this.prisma.manager.findMany(args);
  }
  async findOne<T extends Prisma.ManagerFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ManagerFindUniqueArgs>
  ): Promise<Manager | null> {
    return this.prisma.manager.findUnique(args);
  }
  async create<T extends Prisma.ManagerCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ManagerCreateArgs>
  ): Promise<Manager> {
    return this.prisma.manager.create<T>(args);
  }
  async update<T extends Prisma.ManagerUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ManagerUpdateArgs>
  ): Promise<Manager> {
    return this.prisma.manager.update<T>(args);
  }
  async delete<T extends Prisma.ManagerDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ManagerDeleteArgs>
  ): Promise<Manager> {
    return this.prisma.manager.delete(args);
  }

  async findCustomers(
    parentId: string,
    args: Prisma.CustomerFindManyArgs
  ): Promise<Customer[]> {
    return this.prisma.manager
      .findUnique({
        where: { id: parentId },
      })
      .customers(args);
  }

  async findItems(
    parentId: string,
    args: Prisma.ItemFindManyArgs
  ): Promise<Item[]> {
    return this.prisma.manager
      .findUnique({
        where: { id: parentId },
      })
      .items(args);
  }

  async findSales(
    parentId: string,
    args: Prisma.SaleFindManyArgs
  ): Promise<Sale[]> {
    return this.prisma.manager
      .findUnique({
        where: { id: parentId },
      })
      .sales(args);
  }

  async findSuppliers(
    parentId: string,
    args: Prisma.SupplierFindManyArgs
  ): Promise<Supplier[]> {
    return this.prisma.manager
      .findUnique({
        where: { id: parentId },
      })
      .suppliers(args);
  }

  async getAdmins(parentId: string): Promise<Admin | null> {
    return this.prisma.manager
      .findUnique({
        where: { id: parentId },
      })
      .admins();
  }

  async getStores(parentId: string): Promise<Store | null> {
    return this.prisma.manager
      .findUnique({
        where: { id: parentId },
      })
      .stores();
  }
}
