/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdminWhereUniqueInput } from "../../admin/base/AdminWhereUniqueInput";
import { ValidateNested, IsOptional, IsString, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { CustomerCreateNestedManyWithoutManagersInput } from "./CustomerCreateNestedManyWithoutManagersInput";
import { ItemCreateNestedManyWithoutManagersInput } from "./ItemCreateNestedManyWithoutManagersInput";
import { SaleCreateNestedManyWithoutManagersInput } from "./SaleCreateNestedManyWithoutManagersInput";
import { StoreWhereUniqueInput } from "../../store/base/StoreWhereUniqueInput";
import { SupplierCreateNestedManyWithoutManagersInput } from "./SupplierCreateNestedManyWithoutManagersInput";
@InputType()
class ManagerCreateInput {
  @ApiProperty({
    required: false,
    type: () => AdminWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdminWhereUniqueInput)
  @IsOptional()
  @Field(() => AdminWhereUniqueInput, {
    nullable: true,
  })
  admins?: AdminWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CustomerCreateNestedManyWithoutManagersInput,
  })
  @ValidateNested()
  @Type(() => CustomerCreateNestedManyWithoutManagersInput)
  @IsOptional()
  @Field(() => CustomerCreateNestedManyWithoutManagersInput, {
    nullable: true,
  })
  customers?: CustomerCreateNestedManyWithoutManagersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  firstName!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  gender!: string;

  @ApiProperty({
    required: false,
    type: () => ItemCreateNestedManyWithoutManagersInput,
  })
  @ValidateNested()
  @Type(() => ItemCreateNestedManyWithoutManagersInput)
  @IsOptional()
  @Field(() => ItemCreateNestedManyWithoutManagersInput, {
    nullable: true,
  })
  items?: ItemCreateNestedManyWithoutManagersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  phoneNumber?: number | null;

  @ApiProperty({
    required: false,
    type: () => SaleCreateNestedManyWithoutManagersInput,
  })
  @ValidateNested()
  @Type(() => SaleCreateNestedManyWithoutManagersInput)
  @IsOptional()
  @Field(() => SaleCreateNestedManyWithoutManagersInput, {
    nullable: true,
  })
  sales?: SaleCreateNestedManyWithoutManagersInput;

  @ApiProperty({
    required: false,
    type: () => StoreWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => StoreWhereUniqueInput)
  @IsOptional()
  @Field(() => StoreWhereUniqueInput, {
    nullable: true,
  })
  stores?: StoreWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => SupplierCreateNestedManyWithoutManagersInput,
  })
  @ValidateNested()
  @Type(() => SupplierCreateNestedManyWithoutManagersInput)
  @IsOptional()
  @Field(() => SupplierCreateNestedManyWithoutManagersInput, {
    nullable: true,
  })
  suppliers?: SupplierCreateNestedManyWithoutManagersInput;
}
export { ManagerCreateInput };
